function(wd_glob_sources)
    cmake_parse_arguments(ARGS "" "" "SHARED;STATIC" ${ARGN})
    file(GLOB static_sources ${ARGS_STATIC})
    file(GLOB both_sources ${ARGS_UNPARSED_ARGUMENTS})
    target_sources(WD_SDL PRIVATE ${static_sources} ${both_sources})
endfunction()

function(wd_include_directories)
    cmake_parse_arguments(ARGS "SYSTEM;BEFORE;AFTER;PRIVATE;PUBLIC;INTERFACE;NO_EXPORT" "" "" ${ARGN})
    set(system "")
    if(ARGS_SYSTEM)
        set(system "SYSTEM")
    endif()
    set(before_after )
    if(ARGS_AFTER)
        set(before_after "AFTER")
    endif()
    if(ARGS_BEFORE)
        if(before_after)
            message(FATAL_ERROR "before and after are exclusive options")
        endif()
        set(before_after "BEFORE")
    endif()
    _get_ARGS_visibility()
    target_include_directories(WD_SDL ${system} ${before_after} ${visibility} ${ARGS_UNPARSED_ARGUMENTS})
endfunction()

macro(_get_ARGS_visibility)
    set(_conflict FALSE)
    set(visibility)
    if(ARGS_PRIVATE)
        set(visibility PRIVATE)
    elseif(ARGS_PUBLIC)
        if(visibility)
            set(_conflict TRUE)
        endif()
        set(visibility PUBLIC)
    elseif(ARGS_INTERFACE)
        if(visibility)
            set(_conflict TRUE)
        endif()
        set(visibility INTERFACE)
    endif()
    if(_conflict OR NOT visibility)
        message(FATAL_ERROR "PRIVATE/PUBLIC/INTERFACE must be used exactly once")
    endif()
    unset(_conflict)
endmacro()